planet
will-0/will-0.github.io pull request #19
Opened 2021-03-16 19:37 UTC by sam-halfpenny

2021-03-17 14:40 UTC, will-0 requested changes
Sick!! A cool game man, where'd you get the idea for this one?

Other than the small change to title, it would also be great to have some instructions. This is just a suggestions so I'll leave it up to you whether you do it, but I think it would be cool the first time you see it :)

2021-03-17 14:40 UTC, will-0 commented on planetbomber/planet.html
> +        <h1>BLOCK RUNNER (random)</h1>
👀👀👀

2021-03-17 14:40 UTC, will-0 commented on planetbomber/planet.html
> +        <h1>BLOCK RUNNER (random)</h1>
Doesn't look like block runner to me :O

2021-03-17 17:23 UTC, sam-halfpenny commented on planetbomber/planet.html
> +        <h1>BLOCK RUNNER (random)</h1>
oh yeah

2021-03-18 10:01 UTC, will-0 approved these changes
Jazzy

2021-03-18 10:01 UTC, merged