Fix c bug
will-0/will-0.github.io pull request #26
Opened 2021-06-21 09:56 UTC by sam-halfpenny

fixed

2021-06-21 16:31 UTC, will-0 approved these changes
Randomly dying

2021-06-21 16:31 UTC, will-0 commented on claustrophobia/claustrophobia.js
> +    if(!end && !dead){
There's no reference to dead in your file. Additionally, switching it back to what it used to be randomly makes you win.

2021-06-21 17:13 UTC, will-0 requested changes

2021-06-21 17:13 UTC, will-0 commented on claustrophobia/claustrophobia.js
> +    if(!end && !dead){
There's no reference to dead in your file. Additionally, switching it back to what it used to be randomly makes you win.

2021-06-23 20:07 UTC, sam-halfpenny commented
i have added hole dodger on to this branch to avoid git conflicts porque no me gusta :sunglasses:

2021-06-23 20:15 UTC, sam-halfpenny commented on claustrophobia/claustrophobia.js
> +    if(!end && !dead){
you will win randomly if all the sheep randomly wander into the red square

2021-06-26 18:58 UTC, sam-halfpenny commented
sorry i figured out what was wrong, i had implanted a kill switch to prevent my computer from exploding when i wanted to log data every frame and i forgot to delete it

2021-07-05 14:48 UTC, will-0 approved these changes
I literally cannot beat this game even when I set it to 57 (which is one square missing)

But it seems to work. Nice job man x

2021-07-05 14:48 UTC, merged