includes jumpyblock
will-0/will-0.github.io pull request #9
Opened 2021-02-01 16:13 UTC by sam-halfpenny

2021-02-02 19:54 UTC, will-0 requested changes
Just minor changes this time, you forgot to change the names for the different games. Tbh I would fix it myself but I want you to check out some of the other comments first.

Alors. It's very jazzy.

2021-02-02 19:54 UTC, will-0 commented on index.html
> +        v1.7.2
lol why ".2"

2021-02-02 19:54 UTC, will-0 commented on jumpyblock/jumpy1.js
> +        }
I diffed the file, this is the only change between jumpy1.js and jumpy2.js:

![image](https://user-images.githubusercontent.com/30996474/106653920-54101180-658f-11eb-8f4d-579a424638a4.png)

Let's have a sit down and think how we can make it so you can change the game by adjusting a few settings, rather than copy and pasting the whole thing!

2021-02-02 19:54 UTC, will-0 commented on jumpyblock/jumpy1.html
> +        <script src="jumpy.js"></script>
I think this is meant to be jumpy1.js

2021-02-02 19:54 UTC, will-0 commented on jumpyblock/jumpy2.html
> +        <script src="jumpy.js"></script>
And I think this one is meant to be jumpy2.js

2021-02-02 20:47 UTC, sam-halfpenny commented on index.html
> +        v1.7.2
because the second num is the web design update level

2021-02-02 20:51 UTC, sam-halfpenny commented on jumpyblock/jumpy1.js
> +        }
yh well i can make it so that the person inputs the difficulty level but i dont think it would be great. would love to know how you would fix this issue i dont know if there is a way of changing variables from the html

2021-02-02 20:52 UTC, sam-halfpenny commented on jumpyblock/jumpy1.html
> +        <script src="jumpy.js"></script>
yh ik but it doesnt really matter

2021-02-02 20:53 UTC, sam-halfpenny commented on jumpyblock/jumpy1.html
> +        <script src="jumpy.js"></script>
o yh

2021-02-02 20:53 UTC, sam-halfpenny commented on jumpyblock/jumpy2.html
> +        <script src="jumpy.js"></script>
o yh

2021-02-02 20:55 UTC, sam-halfpenny commented
will as i said in my text on Whatsapp my computer is not letting me turn it on so i will not be able to fix any problems with the code until its fixed so it may take a while before i commit again

2021-02-02 20:57 UTC, will-0 commented on index.html
> +        v1.7.2
Might make more sense to have that second then, since you're likely to add games more frequently

2021-02-02 20:58 UTC, will-0 commented on jumpyblock/jumpy1.js
> +        }
Hehe dw I will got chooooo

2021-02-03 08:52 UTC, sam-halfpenny commented on index.html
> +        v1.7.2
tbh I don't really mind

2021-02-03 08:53 UTC, sam-halfpenny commented on jumpyblock/jumpy1.js
> +        }
that makes complete sense

2021-02-05 08:26 UTC, sam-halfpenny commented on jumpyblock/jumpy1.html
> +        <script src="jumpy.js"></script>
i should have fixed it but as i did it online i cant check it but it should be good :)

2021-02-05 08:27 UTC, sam-halfpenny commented on jumpyblock/jumpy2.html
> +        <script src="jumpy.js"></script>
^read comment above

2021-02-05 14:14 UTC, will-0 approved these changes
Noice

2021-02-05 14:15 UTC, merged